import time
import random
import psutil
import json
import os
import sys
import threading
import subprocess
import urllib.request
import urllib.error

# Ensure we can import from the Apollo root
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

# Configuration
IDLE_CPU_THRESHOLD = 15.0  # If CPU is above 15%, system is not idle
IDLE_GPU_THRESHOLD = 15.0  # If EWMA GPU usage is above 15%, system is not idle
CHECK_INTERVAL = 60        # Check every 60 seconds
DAYDREAM_COOLDOWN = 600    # Wait 10 minutes between daydreams
PAUSE_FILE = "/mnt/TG_2TB/Projects/Apollo/daydream_pause.lock" 
CHRONOLOGY_FILE = "/mnt/TG_2TB/Projects/Apollo/APOLLO_CHRONOLOGY.md"
API_URL = "http://localhost:8082/v1/chat/completions"

# --- GPU EWMA Monitor ---
gpu_ewma = 0.0
gpu_ewma_lock = threading.Lock()

def gpu_monitor_loop():
    global gpu_ewma
    alpha = 0.2 # Smoothing factor. Lower = slower response.
    while True:
        try:
            res = subprocess.run(["rocm-smi", "-u", "--json"], capture_output=True, text=True)
            stdout = res.stdout
            start_idx = stdout.find('{')
            current_usage = 0.0
            if start_idx != -1:
                data = json.loads(stdout[start_idx:])
                for card in data:
                    if isinstance(data[card], dict) and "GPU use (%)" in data[card]:
                        current_usage = float(data[card]["GPU use (%)"])
                        break
            
            with gpu_ewma_lock:
                gpu_ewma = (alpha * current_usage) + ((1 - alpha) * gpu_ewma)
        except Exception:
            pass
        time.sleep(2) # Sample every 2 seconds

threading.Thread(target=gpu_monitor_loop, daemon=True).start()
# ------------------------

def is_system_idle():
    """Checks if the system is considered 'idle' based on CPU usage, GPU EWMA, and pause lock."""
    if os.path.exists(PAUSE_FILE):
        return False
    
    with gpu_ewma_lock:
        current_gpu_ewma = gpu_ewma
        
    if current_gpu_ewma > IDLE_GPU_THRESHOLD:
        return False
    
    # Check CPU usage over a 3-second window
    cpu_percent = psutil.cpu_percent(interval=3)
    if cpu_percent > IDLE_CPU_THRESHOLD:
        return False
    
    return True

def get_chronology_chunks():
    """Parses the APOLLO_CHRONOLOGY.md to extract recent and historical context."""
    if not os.path.exists(CHRONOLOGY_FILE):
        print(f"Chronology file not found: {CHRONOLOGY_FILE}")
        return None, None
    
    with open(CHRONOLOGY_FILE, "r", encoding="utf-8") as f:
        content = f.read()
        
    # Split by the standard date headers generated by the diary script
    chunks = content.split("\n## 2025-")
    if len(chunks) < 2:
        return None, None
        
    # Re-attach the split string to maintain formatting
    entries = ["## 2025-" + c for c in chunks[1:]]
    
    if not entries:
        return None, None
        
    # The last chunk is our most recent struggle
    recent_chunk = entries[-1]
    
    # Pick a random historical chunk to spark creative connections
    if len(entries) > 1:
        historical_chunk = random.choice(entries[:-1])
    else:
        historical_chunk = None
        
    # Limit chunk size to prevent blowing up the context window unnecessarily
    return recent_chunk[:8000], (historical_chunk[:8000] if historical_chunk else None)

def call_llm(messages, temperature=1.0, response_format=None):
    """Wrapper for interacting with the local llama-server via OpenAI API format."""
    payload = {
        "messages": messages,
        "temperature": temperature,
        "max_tokens": 4096
    }
    if response_format:
        payload["response_format"] = response_format
        
    try:
        req = urllib.request.Request(
            API_URL,
            data=json.dumps(payload).encode('utf-8'),
            headers={'Content-Type': 'application/json'}
        )
        with urllib.request.urlopen(req, timeout=300) as res:
            data = json.loads(res.read().decode('utf-8'))
        return data['choices'][0]['message']['content'].strip()
    except urllib.error.URLError as e:
        print(f"LLM API Error: {e}")
        return None

def trigger_daydream():
    """Executes the dual-pass daydream logic using the Master Chronology."""
    print("🧠 System idle. Initiating Daydream V2 sequence...")
    
    recent, historical = get_chronology_chunks()
    if not recent:
        print("Not enough history in chronology yet.")
        return

    context_str = f"--- RECENT STRUGGLES ---\n{recent}\n\n"
    if historical:
        context_str += f"--- RANDOM HISTORICAL CONTEXT ---\n{historical}\n\n"

    # ==========================================
    # PASS 1: The Dreamer (Idea Generation)
    # ==========================================
    print("💭 Pass 1: Generating Epiphany...")
    dreamer_sys = (
        "You are Apollo's subconscious 'Default Mode Network'.\n"
        "Review the provided chronological development history. "
        "Identify an unresolved bug, an architectural inefficiency, or a missing connection. "
        "Think deeply about it and propose a concrete, actionable solution or architectural plan."
    )
    dreamer_user = f"Here is the context:\n{context_str}\n\nWhat actionable epiphany can you derive from this? Provide a detailed thought process followed by the concrete plan."
    
    epiphany_text = call_llm([
        {"role": "system", "content": dreamer_sys},
        {"role": "user", "content": dreamer_user}
    ], temperature=1.0) # High temperature for creativity
    
    if not epiphany_text:
        return
        
    print(f"\n=== ✨ RAW EPIPHANY ===\n{epiphany_text}\n======================\n")

    # ==========================================
    # PASS 2: The Filter (Actionability Check)
    # ==========================================
    print("🛡️ Pass 2: Filtering for Actionability (Guided Decoding)...")
    filter_sys = (
        "You are the Sovereign Coordinator. Your job is to act as a strict filter for daydreams.\n"
        "Evaluate the provided epiphany. Is it a concrete, actionable code/architecture plan that can be implemented by an autonomous agent?\n"
        "If it is just philosophical rambling, vague ideas, or already completed work, reject it."
    )
    filter_user = (
        f"Evaluate this epiphany:\n{epiphany_text}\n\n"
        "Respond in strict JSON format."
    )
    
    # Leverage llama.cpp's native Guided Decoding (GBNF) to force JSON output
    response_format = {
        "type": "json_schema", 
        "json_schema": {
            "name": "epiphany_filter", 
            "schema": {
                "type": "object", 
                "properties": {
                    "is_actionable": {"type": "boolean"}, 
                    "reasoning": {"type": "string"}
                },
                "required": ["is_actionable", "reasoning"]
            }
        }
    }
    
    filter_result = call_llm([
        {"role": "system", "content": filter_sys},
        {"role": "user", "content": filter_user}
    ], temperature=0.1, response_format=response_format) # Low temp for strict logic
    
    if not filter_result:
        return
        
    try:
        verdict = json.loads(filter_result)
        print(f"Filter Verdict: Actionable={verdict.get('is_actionable')} | {verdict.get('reasoning')}")
        
        if verdict.get("is_actionable"):
            # Save strictly actionable items to the new queue
            os.makedirs("/mnt/TG_2TB/Projects/Apollo/data", exist_ok=True)
            with open("/mnt/TG_2TB/Projects/Apollo/data/actionable_epiphanies.jsonl", "a", encoding="utf-8") as f:
                record = {
                    "timestamp": time.time(),
                    "epiphany": epiphany_text,
                    "reasoning": verdict.get("reasoning")
                }
                f.write(json.dumps(record) + "\n")
            print("💾 Actionable epiphany saved to data/actionable_epiphanies.jsonl")
        else:
            print("🗑️ Epiphany discarded as non-actionable noise.")
            
    except json.JSONDecodeError:
        print("Failed to parse Filter JSON output.")

def main():
    print("🌙 Daydream Daemon V2 Started. Monitoring system state...")
    try:
        while True:
            if is_system_idle():
                trigger_daydream()
                print(f"💤 Daydream V2 complete. Resting for {DAYDREAM_COOLDOWN} seconds.")
                time.sleep(DAYDREAM_COOLDOWN)
            else:
                # System is busy, check again later
                time.sleep(CHECK_INTERVAL)
    except KeyboardInterrupt:
        print("\nDaydream Daemon V2 shutting down.")

if __name__ == "__main__":
    main()
