#!/usr/bin/env python3
"""Flash-Next decode matmul shapes -> test-backend-ops perf cases (PREREG_SM60_TYPES.md).
Reads tables/*.tsv (name, ggml type id, bytes, dims ne0xne1[xne2]); emits the unique (type, k=ne0, m=ne1[, experts]) set.
Dense: every 2-D weight except token_embd, per_layer_token_embd and ssm_conv1d (a conv, not a matmul).
Experts (3-D *_exps): MUL_MAT_ID with 512 experts, 10 used (qwen4exp.expert_count / expert_used_count)."""
import sys
from pathlib import Path
H = Path(__file__).resolve().parent
NAMES = {0: "F32", 1: "F16", 2: "Q4_0", 3: "Q4_1", 6: "Q5_0", 7: "Q5_1", 8: "Q8_0", 10: "Q2_K", 11: "Q3_K", 12: "Q4_K",
         13: "Q5_K", 14: "Q6_K", 16: "IQ2_XXS", 17: "IQ2_XS", 18: "IQ3_XXS", 19: "IQ1_S", 20: "IQ4_NL", 21: "IQ3_S",
         22: "IQ2_S", 23: "IQ4_XS", 29: "IQ1_M", 30: "BF16", 42: "Q2_0"}
SKIP = ("token_embd.weight", "per_layer_token_embd.weight", "ssm_conv1d.weight")
N_EXPERT, N_USED = 512, 10


def tensors(table):
    for l in open(table):
        _, name, t, size, dims = l.rstrip("\n").split("\t")
        ne = [int(x) for x in dims.split("x")]
        if len(ne) < 2 or name.endswith(SKIP):
            continue
        yield name, NAMES[int(t)], int(size), ne


def cases(tables):
    dense, moe = set(), set()
    for tb in tables:
        for name, t, size, ne in tensors(tb):
            (moe if len(ne) == 3 else dense).add((t, ne[0], ne[1]))
    return sorted(dense), sorted(moe)


if __name__ == "__main__":
    dense, moe = cases(sorted((H / "tables").glob("*.tsv")))
    print("    // Flash-Next decode shapes, generated by data/receipts/sm60-types/fn_cases.py (PREREG_SM60_TYPES.md)")
    for t, k, m in dense:
        print(f"    test_cases.emplace_back(new test_mul_mat(GGML_TYPE_{t}, GGML_TYPE_F32, {m}, 1, {k}, {{1, 1}}, {{1, 1}}));")
    for t, k, m in moe:
        print(f"    test_cases.emplace_back(new test_mul_mat_id(GGML_TYPE_{t}, GGML_TYPE_F32, {N_EXPERT}, {N_USED}, false, {m}, 1, {k}));")
    print(f"// {len(dense)} dense + {len(moe)} expert cases", file=sys.stderr)
